Vagrant.configure("2") do |config|
	config.vm.define "vmid1" do |vmid1|
		config.vm.box = "ubuntu/trusty64"
		config.vm.network "private_network", ip: "192.168.50.1"
		config.vm.hostname = "goncharov_vmid_1"
		config.vm.provider :virtualbox do |vb|
			vb.name = "goncharovVMID1" 
			vb.gui = true
			vb.cpus = 1
			vb.memory = "512"
		end
	end
end