Vagrant.configure("2") do |config|
	config.vm.define "vmid3" do |vmid3|
		config.vm.box = "ubuntu/trusty64"
		config.vm.network "private_network", ip: "192.168.50.3"
		config.vm.hostname = "goncharov_vmid_3"
		config.vm.provider :virtualbox do |vb|
			vb.name = "goncharovVMID3" 
			vb.gui = true
			vb.cpus = 1
			vb.memory = "512"
		end
	end
end