Vagrant.configure("2") do |config|
	config.vm.define "vmid2" do |vmid2|
		config.vm.box = "ubuntu/trusty64"
		config.vm.network "private_network", ip: "192.168.50.2"
		config.vm.hostname = "goncharov_vmid_2"
		config.vm.provider :virtualbox do |vb|
			vb.name = "goncharovVMID2" 
			vb.gui = true
			vb.cpus = 1
			vb.memory = "512"
		end
	end
end